# Generated by Django 3.2.3 on 2022-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceID', models.CharField(max_length=20)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('faceVector', models.CharField(blank=True, max_length=20000)),
                ('faceData', models.CharField(blank=True, max_length=250000)),
            ],
        ),
    ]
