# Generated by Django 3.2.3 on 2022-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceobject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceobject',
            name='faceData',
            field=models.CharField(blank=True, max_length=2500000),
        ),
    ]
