# Generated by Django 3.2.3 on 2022-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20220824_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='wifiName',
            field=models.CharField(default='ssid', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='wifiPass',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
