# Generated by Django 3.2.3 on 2022-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logobject_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logobject',
            name='timeStamp',
            field=models.DateTimeField(blank=True, max_length=30),
        ),
    ]
