# Generated by Django 3.2.3 on 2022-08-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logobject_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField()),
                ('timeStamp', models.DateTimeField(max_length=30)),
                ('faceData', models.CharField(max_length=250000)),
            ],
        ),
        migrations.DeleteModel(
            name='LogObject',
        ),
    ]
