# Generated by Django 3.2.3 on 2022-08-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceobject', '0001_initial'),
        ('logs', '0004_auto_20220802_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameData', models.CharField(max_length=250000)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='objectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceobject.faceobject'),
        ),
        migrations.AddField(
            model_name='log',
            name='frameID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.framelog'),
        ),
    ]
