# Generated by Django 3.2.3 on 2022-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20220802_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='frameID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='objectID',
            field=models.IntegerField(null=True),
        ),
    ]
