# Generated by Django 3.2.3 on 2022-08-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20220802_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='bbox',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
